version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
